Suppress -Wsingle-bit-bitfield-constant-conversion warnings
Some single-bit bitfields are declared as int, and Clang 16 now emits warnings
for such uses, e.g.

.../flang1exe/commopt.c:389:23: error: implicit truncation from 'int' to a
one-bit wide bit-field changes value from 1 to -1

Such bitfields should be declared unsigned instead.