Fixed missing prototype error reported by Clang 15
error: passing arguments to 'GetVolumeInformationA' without a prototype
is deprecated in all versions of C and is not supported in C2x
[-Werror,-Wdeprecated-non-prototype].

Also removed the superfluous x86 case.
Added proper Windows types for 'GetVolumeInformationA' function.