[runtime] Fix -Wcast-qual warnings
Since upgrading to Clang/LLVM 17, the Classic Flang build now fails with a
large number of errors with this message:

error: cast from 'const char *' to 'char *' drops const qualifier [-Werror,-Wcast-qual]

This patch fixes all such warnings in runtime/.