[runtime] Remove extern function declarations
`extern` function declarations have been replaced by headers (standard headers
if possible), except for single unique uses. This not only reduces code
duplication, but also fixes `-Wdeprecated-non-prototype` warnings, e.g.

.../flang/runtime/flang/curdir.c:25:14: error: a function declaration without a
prototype is deprecated in all versions of C and is treated as a zero-parameter
prototype in C2x, conflicting with a previous declaration
[-Werror,-Wdeprecated-non-prototype]
extern char *getcwd();
             ^
/usr/include/unistd.h:514:14: note: conflicting prototype is here
extern char *getcwd (char *__buf, size_t __size) __THROW __wur;
             ^

Some other dead code is also removed.