[runtime] Add C prototypes for external Fortran matmul functions
This fixes errors such as:

.../flang/runtime/flang/mmreal8.c:99:21: error: passing arguments to
'ftn_mvmul_real8_' without a prototype is deprecated in all versions of C
and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
    ftn_mvmul_real8_(&ta, &mra, &kab, alpha, a, &lda, b, beta, c);
                    ^